## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 1s

#filebeat.autodiscover:
#  providers:
#    # The Docker autodiscover provider automatically retrieves logs from Docker
#    # containers as they start and stop.
#    - type: docker
#      hints.enabled: true
filebeat.modules:
- module: mysql
  slowlog:
    enabled: true
    var.paths: [ "/var/log/mysql/slow-query.log" ]
processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: ${ELASTIC_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

setup.dashboards.enabled: true

setup.kibana.host: "http://kibana:5601"

http.enabled: true
http.host: 0.0.0.0
